// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'IdentificationFailedBannedMessage.xml' the '04/04/2012 14:27:19'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class IdentificationFailedBannedMessage : IdentificationFailedMessage
	{
		public const uint Id = 6174;
		public override uint MessageId
		{
			get
			{
				return 6174;
			}
		}
		
		public double banEndDate;
		
		public IdentificationFailedBannedMessage()
		{
		}
		
		public IdentificationFailedBannedMessage(sbyte reason, double banEndDate)
			 : base(reason)
		{
			this.banEndDate = banEndDate;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteDouble(banEndDate);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			banEndDate = reader.ReadDouble();
			if ( banEndDate < 0 )
			{
				throw new Exception("Forbidden value on banEndDate = " + banEndDate + ", it doesn't respect the following condition : banEndDate < 0");
			}
		}
	}
}
