// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'SelectedServerRefusedMessage.xml' the '04/04/2012 14:27:19'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class SelectedServerRefusedMessage : Message
	{
		public const uint Id = 41;
		public override uint MessageId
		{
			get
			{
				return 41;
			}
		}
		
		public short serverId;
		public sbyte error;
		public sbyte serverStatus;
		
		public SelectedServerRefusedMessage()
		{
		}
		
		public SelectedServerRefusedMessage(short serverId, sbyte error, sbyte serverStatus)
		{
			this.serverId = serverId;
			this.error = error;
			this.serverStatus = serverStatus;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteShort(serverId);
			writer.WriteSByte(error);
			writer.WriteSByte(serverStatus);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			serverId = reader.ReadShort();
			error = reader.ReadSByte();
			if ( error < 0 )
			{
				throw new Exception("Forbidden value on error = " + error + ", it doesn't respect the following condition : error < 0");
			}
			serverStatus = reader.ReadSByte();
			if ( serverStatus < 0 )
			{
				throw new Exception("Forbidden value on serverStatus = " + serverStatus + ", it doesn't respect the following condition : serverStatus < 0");
			}
		}
	}
}
