// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ServersListMessage.xml' the '04/04/2012 14:27:19'
using System;
using Stump.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace Stump.DofusProtocol.Messages
{
	public class ServersListMessage : Message
	{
		public const uint Id = 30;
		public override uint MessageId
		{
			get
			{
				return 30;
			}
		}
		
		public IEnumerable<Types.GameServerInformations> servers;
		
		public ServersListMessage()
		{
		}
		
		public ServersListMessage(IEnumerable<Types.GameServerInformations> servers)
		{
			this.servers = servers;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)servers.Count());
			foreach (var entry in servers)
			{
				entry.Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			servers = new Types.GameServerInformations[limit];
			for (int i = 0; i < limit; i++)
			{
				(servers as Types.GameServerInformations[])[i] = new Types.GameServerInformations();
				(servers as Types.GameServerInformations[])[i].Deserialize(reader);
			}
		}
	}
}
