// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'StatsUpgradeResultMessage.xml' the '04/04/2012 14:27:30'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class StatsUpgradeResultMessage : Message
	{
		public const uint Id = 5609;
		public override uint MessageId
		{
			get
			{
				return 5609;
			}
		}
		
		public short nbCharacBoost;
		
		public StatsUpgradeResultMessage()
		{
		}
		
		public StatsUpgradeResultMessage(short nbCharacBoost)
		{
			this.nbCharacBoost = nbCharacBoost;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteShort(nbCharacBoost);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			nbCharacBoost = reader.ReadShort();
			if ( nbCharacBoost < 0 )
			{
				throw new Exception("Forbidden value on nbCharacBoost = " + nbCharacBoost + ", it doesn't respect the following condition : nbCharacBoost < 0");
			}
		}
	}
}
