// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'LeaveDialogMessage.xml' the '04/04/2012 14:27:30'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class LeaveDialogMessage : Message
	{
		public const uint Id = 5502;
		public override uint MessageId
		{
			get
			{
				return 5502;
			}
		}
		
		public sbyte dialogType;
		
		public LeaveDialogMessage()
		{
		}
		
		public LeaveDialogMessage(sbyte dialogType)
		{
			this.dialogType = dialogType;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(dialogType);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			dialogType = reader.ReadSByte();
			if ( dialogType < 0 )
			{
				throw new Exception("Forbidden value on dialogType = " + dialogType + ", it doesn't respect the following condition : dialogType < 0");
			}
		}
	}
}
