// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ChatAbstractServerMessage.xml' the '04/04/2012 14:27:22'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ChatAbstractServerMessage : Message
	{
		public const uint Id = 880;
		public override uint MessageId
		{
			get
			{
				return 880;
			}
		}
		
		public sbyte channel;
		public string content;
		public int timestamp;
		public string fingerprint;
		
		public ChatAbstractServerMessage()
		{
		}
		
		public ChatAbstractServerMessage(sbyte channel, string content, int timestamp, string fingerprint)
		{
			this.channel = channel;
			this.content = content;
			this.timestamp = timestamp;
			this.fingerprint = fingerprint;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(channel);
			writer.WriteUTF(content);
			writer.WriteInt(timestamp);
			writer.WriteUTF(fingerprint);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			channel = reader.ReadSByte();
			if ( channel < 0 )
			{
				throw new Exception("Forbidden value on channel = " + channel + ", it doesn't respect the following condition : channel < 0");
			}
			content = reader.ReadUTF();
			timestamp = reader.ReadInt();
			if ( timestamp < 0 )
			{
				throw new Exception("Forbidden value on timestamp = " + timestamp + ", it doesn't respect the following condition : timestamp < 0");
			}
			fingerprint = reader.ReadUTF();
		}
	}
}
