// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameRolePlayMerchantInformations.xml' the '04/04/2012 14:27:37'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class GameRolePlayMerchantInformations : GameRolePlayNamedActorInformations
	{
		public const uint Id = 129;
		public override short TypeId
		{
			get
			{
				return 129;
			}
		}
		
		public int sellType;
		
		public GameRolePlayMerchantInformations()
		{
		}
		
		public GameRolePlayMerchantInformations(int contextualId, Types.EntityLook look, Types.EntityDispositionInformations disposition, string name, int sellType)
			 : base(contextualId, look, disposition, name)
		{
			this.sellType = sellType;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(sellType);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			sellType = reader.ReadInt();
			if ( sellType < 0 )
			{
				throw new Exception("Forbidden value on sellType = " + sellType + ", it doesn't respect the following condition : sellType < 0");
			}
		}
	}
}
