// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightResultMutantListEntry.xml' the '04/04/2012 14:27:37'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class FightResultMutantListEntry : FightResultFighterListEntry
	{
		public const uint Id = 216;
		public override short TypeId
		{
			get
			{
				return 216;
			}
		}
		
		public ushort level;
		
		public FightResultMutantListEntry()
		{
		}
		
		public FightResultMutantListEntry(short outcome, Types.FightLoot rewards, int id, bool alive, ushort level)
			 : base(outcome, rewards, id, alive)
		{
			this.level = level;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteUShort(level);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			level = reader.ReadUShort();
			if ( level < 0 || level > 65535 )
			{
				throw new Exception("Forbidden value on level = " + level + ", it doesn't respect the following condition : level < 0 || level > 65535");
			}
		}
	}
}
