// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightResultFighterListEntry.xml' the '04/04/2012 14:27:37'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class FightResultFighterListEntry : FightResultListEntry
	{
		public const uint Id = 189;
		public override short TypeId
		{
			get
			{
				return 189;
			}
		}
		
		public int id;
		public bool alive;
		
		public FightResultFighterListEntry()
		{
		}
		
		public FightResultFighterListEntry(short outcome, Types.FightLoot rewards, int id, bool alive)
			 : base(outcome, rewards)
		{
			this.id = id;
			this.alive = alive;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(id);
			writer.WriteBoolean(alive);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			id = reader.ReadInt();
			alive = reader.ReadBoolean();
		}
	}
}
