// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MountInformationInPaddockRequestMessage.xml' the '04/04/2012 14:27:24'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class MountInformationInPaddockRequestMessage : Message
	{
		public const uint Id = 5975;
		public override uint MessageId
		{
			get
			{
				return 5975;
			}
		}
		
		public int mapRideId;
		
		public MountInformationInPaddockRequestMessage()
		{
		}
		
		public MountInformationInPaddockRequestMessage(int mapRideId)
		{
			this.mapRideId = mapRideId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(mapRideId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			mapRideId = reader.ReadInt();
		}
	}
}
