// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PaddockMoveItemRequestMessage.xml' the '04/04/2012 14:27:24'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class PaddockMoveItemRequestMessage : Message
	{
		public const uint Id = 6052;
		public override uint MessageId
		{
			get
			{
				return 6052;
			}
		}
		
		public short oldCellId;
		public short newCellId;
		
		public PaddockMoveItemRequestMessage()
		{
		}
		
		public PaddockMoveItemRequestMessage(short oldCellId, short newCellId)
		{
			this.oldCellId = oldCellId;
			this.newCellId = newCellId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteShort(oldCellId);
			writer.WriteShort(newCellId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			oldCellId = reader.ReadShort();
			if ( oldCellId < 0 || oldCellId > 559 )
			{
				throw new Exception("Forbidden value on oldCellId = " + oldCellId + ", it doesn't respect the following condition : oldCellId < 0 || oldCellId > 559");
			}
			newCellId = reader.ReadShort();
			if ( newCellId < 0 || newCellId > 559 )
			{
				throw new Exception("Forbidden value on newCellId = " + newCellId + ", it doesn't respect the following condition : newCellId < 0 || newCellId > 559");
			}
		}
	}
}
