// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'UpdateLifePointsMessage.xml' the '04/04/2012 14:27:22'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class UpdateLifePointsMessage : Message
	{
		public const uint Id = 5658;
		public override uint MessageId
		{
			get
			{
				return 5658;
			}
		}
		
		public int lifePoints;
		public int maxLifePoints;
		
		public UpdateLifePointsMessage()
		{
		}
		
		public UpdateLifePointsMessage(int lifePoints, int maxLifePoints)
		{
			this.lifePoints = lifePoints;
			this.maxLifePoints = maxLifePoints;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(lifePoints);
			writer.WriteInt(maxLifePoints);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			lifePoints = reader.ReadInt();
			if ( lifePoints < 0 )
			{
				throw new Exception("Forbidden value on lifePoints = " + lifePoints + ", it doesn't respect the following condition : lifePoints < 0");
			}
			maxLifePoints = reader.ReadInt();
			if ( maxLifePoints < 0 )
			{
				throw new Exception("Forbidden value on maxLifePoints = " + maxLifePoints + ", it doesn't respect the following condition : maxLifePoints < 0");
			}
		}
	}
}
