// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameMapMovementMessage.xml' the '04/04/2012 14:27:23'
using System;
using Stump.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace Stump.DofusProtocol.Messages
{
	public class GameMapMovementMessage : Message
	{
		public const uint Id = 951;
		public override uint MessageId
		{
			get
			{
				return 951;
			}
		}
		
		public IEnumerable<short> keyMovements;
		public int actorId;
		
		public GameMapMovementMessage()
		{
		}
		
		public GameMapMovementMessage(IEnumerable<short> keyMovements, int actorId)
		{
			this.keyMovements = keyMovements;
			this.actorId = actorId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)keyMovements.Count());
			foreach (var entry in keyMovements)
			{
				writer.WriteShort(entry);
			}
			writer.WriteInt(actorId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			keyMovements = new short[limit];
			for (int i = 0; i < limit; i++)
			{
				(keyMovements as short[])[i] = reader.ReadShort();
			}
			actorId = reader.ReadInt();
		}
	}
}
