// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'InventoryPresetSaveMessage.xml' the '04/04/2012 14:27:35'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class InventoryPresetSaveMessage : Message
	{
		public const uint Id = 6165;
		public override uint MessageId
		{
			get
			{
				return 6165;
			}
		}
		
		public sbyte presetId;
		public sbyte symbolId;
		public bool saveEquipment;
		
		public InventoryPresetSaveMessage()
		{
		}
		
		public InventoryPresetSaveMessage(sbyte presetId, sbyte symbolId, bool saveEquipment)
		{
			this.presetId = presetId;
			this.symbolId = symbolId;
			this.saveEquipment = saveEquipment;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(presetId);
			writer.WriteSByte(symbolId);
			writer.WriteBoolean(saveEquipment);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			presetId = reader.ReadSByte();
			if ( presetId < 0 )
			{
				throw new Exception("Forbidden value on presetId = " + presetId + ", it doesn't respect the following condition : presetId < 0");
			}
			symbolId = reader.ReadSByte();
			if ( symbolId < 0 )
			{
				throw new Exception("Forbidden value on symbolId = " + symbolId + ", it doesn't respect the following condition : symbolId < 0");
			}
			saveEquipment = reader.ReadBoolean();
		}
	}
}
