// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'BasicNoOperationMessage.xml' the '04/04/2012 14:27:21'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class BasicNoOperationMessage : Message
	{
		public const uint Id = 176;
		public override uint MessageId
		{
			get
			{
				return 176;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
