// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'BasicSwitchModeRequestMessage.xml' the '04/04/2012 14:27:21'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class BasicSwitchModeRequestMessage : Message
	{
		public const uint Id = 6101;
		public override uint MessageId
		{
			get
			{
				return 6101;
			}
		}
		
		public sbyte mode;
		
		public BasicSwitchModeRequestMessage()
		{
		}
		
		public BasicSwitchModeRequestMessage(sbyte mode)
		{
			this.mode = mode;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(mode);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			mode = reader.ReadSByte();
		}
	}
}
