// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'SequenceNumberMessage.xml' the '04/04/2012 14:27:22'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class SequenceNumberMessage : Message
	{
		public const uint Id = 6317;
		public override uint MessageId
		{
			get
			{
				return 6317;
			}
		}
		
		public ushort number;
		
		public SequenceNumberMessage()
		{
		}
		
		public SequenceNumberMessage(ushort number)
		{
			this.number = number;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort(number);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			number = reader.ReadUShort();
			if ( number < 0 || number > 65535 )
			{
				throw new Exception("Forbidden value on number = " + number + ", it doesn't respect the following condition : number < 0 || number > 65535");
			}
		}
	}
}
