// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'SetCharacterRestrictionsMessage.xml' the '04/04/2012 14:27:31'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class SetCharacterRestrictionsMessage : Message
	{
		public const uint Id = 170;
		public override uint MessageId
		{
			get
			{
				return 170;
			}
		}
		
		public Types.ActorRestrictionsInformations restrictions;
		
		public SetCharacterRestrictionsMessage()
		{
		}
		
		public SetCharacterRestrictionsMessage(Types.ActorRestrictionsInformations restrictions)
		{
			this.restrictions = restrictions;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			restrictions.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			restrictions = new Types.ActorRestrictionsInformations();
			restrictions.Deserialize(reader);
		}
	}
}
