// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeObjectRemovedFromBagMessage.xml' the '04/04/2012 14:27:34'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeObjectRemovedFromBagMessage : ExchangeObjectMessage
	{
		public const uint Id = 6010;
		public override uint MessageId
		{
			get
			{
				return 6010;
			}
		}
		
		public int objectUID;
		
		public ExchangeObjectRemovedFromBagMessage()
		{
		}
		
		public ExchangeObjectRemovedFromBagMessage(bool remote, int objectUID)
			 : base(remote)
		{
			this.objectUID = objectUID;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(objectUID);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			objectUID = reader.ReadInt();
			if ( objectUID < 0 )
			{
				throw new Exception("Forbidden value on objectUID = " + objectUID + ", it doesn't respect the following condition : objectUID < 0");
			}
		}
	}
}
