// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeObjectRemovedMessage.xml' the '04/04/2012 14:27:34'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeObjectRemovedMessage : ExchangeObjectMessage
	{
		public const uint Id = 5517;
		public override uint MessageId
		{
			get
			{
				return 5517;
			}
		}
		
		public int objectUID;
		
		public ExchangeObjectRemovedMessage()
		{
		}
		
		public ExchangeObjectRemovedMessage(bool remote, int objectUID)
			 : base(remote)
		{
			this.objectUID = objectUID;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(objectUID);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			objectUID = reader.ReadInt();
			if ( objectUID < 0 )
			{
				throw new Exception("Forbidden value on objectUID = " + objectUID + ", it doesn't respect the following condition : objectUID < 0");
			}
		}
	}
}
