// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ObjectMovementMessage.xml' the '04/04/2012 14:27:34'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ObjectMovementMessage : Message
	{
		public const uint Id = 3010;
		public override uint MessageId
		{
			get
			{
				return 3010;
			}
		}
		
		public int objectUID;
		public byte position;
		
		public ObjectMovementMessage()
		{
		}
		
		public ObjectMovementMessage(int objectUID, byte position)
		{
			this.objectUID = objectUID;
			this.position = position;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(objectUID);
			writer.WriteByte(position);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			objectUID = reader.ReadInt();
			if ( objectUID < 0 )
			{
				throw new Exception("Forbidden value on objectUID = " + objectUID + ", it doesn't respect the following condition : objectUID < 0");
			}
			position = reader.ReadByte();
			if ( position < 0 || position > 255 )
			{
				throw new Exception("Forbidden value on position = " + position + ", it doesn't respect the following condition : position < 0 || position > 255");
			}
		}
	}
}
