// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ObjectAddedMessage.xml' the '04/04/2012 14:27:34'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ObjectAddedMessage : Message
	{
		public const uint Id = 3025;
		public override uint MessageId
		{
			get
			{
				return 3025;
			}
		}
		
		public Types.ObjectItem @object;
		
		public ObjectAddedMessage()
		{
		}
		
		public ObjectAddedMessage(Types.ObjectItem @object)
		{
			this.@object = @object;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			@object.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			@object = new Types.ObjectItem();
			@object.Deserialize(reader);
		}
	}
}
