// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuildInvitationStateRecruterMessage.xml' the '04/04/2012 14:27:31'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GuildInvitationStateRecruterMessage : Message
	{
		public const uint Id = 5563;
		public override uint MessageId
		{
			get
			{
				return 5563;
			}
		}
		
		public string recrutedName;
		public sbyte invitationState;
		
		public GuildInvitationStateRecruterMessage()
		{
		}
		
		public GuildInvitationStateRecruterMessage(string recrutedName, sbyte invitationState)
		{
			this.recrutedName = recrutedName;
			this.invitationState = invitationState;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUTF(recrutedName);
			writer.WriteSByte(invitationState);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			recrutedName = reader.ReadUTF();
			invitationState = reader.ReadSByte();
			if ( invitationState < 0 )
			{
				throw new Exception("Forbidden value on invitationState = " + invitationState + ", it doesn't respect the following condition : invitationState < 0");
			}
		}
	}
}
