// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuildInvitationByNameMessage.xml' the '04/04/2012 14:27:31'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GuildInvitationByNameMessage : Message
	{
		public const uint Id = 6115;
		public override uint MessageId
		{
			get
			{
				return 6115;
			}
		}
		
		public string name;
		
		public GuildInvitationByNameMessage()
		{
		}
		
		public GuildInvitationByNameMessage(string name)
		{
			this.name = name;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUTF(name);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			name = reader.ReadUTF();
		}
	}
}
