// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartInfoMessage.xml' the '04/04/2012 14:27:36'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class PartInfoMessage : Message
	{
		public const uint Id = 1508;
		public override uint MessageId
		{
			get
			{
				return 1508;
			}
		}
		
		public Types.ContentPart part;
		public float installationPercent;
		
		public PartInfoMessage()
		{
		}
		
		public PartInfoMessage(Types.ContentPart part, float installationPercent)
		{
			this.part = part;
			this.installationPercent = installationPercent;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			part.Serialize(writer);
			writer.WriteFloat(installationPercent);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			part = new Types.ContentPart();
			part.Deserialize(reader);
			installationPercent = reader.ReadFloat();
		}
	}
}
