// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'SpellUpgradeSuccessMessage.xml' the '04/04/2012 14:27:30'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class SpellUpgradeSuccessMessage : Message
	{
		public const uint Id = 1201;
		public override uint MessageId
		{
			get
			{
				return 1201;
			}
		}
		
		public int spellId;
		public sbyte spellLevel;
		
		public SpellUpgradeSuccessMessage()
		{
		}
		
		public SpellUpgradeSuccessMessage(int spellId, sbyte spellLevel)
		{
			this.spellId = spellId;
			this.spellLevel = spellLevel;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(spellId);
			writer.WriteSByte(spellLevel);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			spellId = reader.ReadInt();
			spellLevel = reader.ReadSByte();
			if ( spellLevel < 1 || spellLevel > 6 )
			{
				throw new Exception("Forbidden value on spellLevel = " + spellLevel + ", it doesn't respect the following condition : spellLevel < 1 || spellLevel > 6");
			}
		}
	}
}
