// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'JobCrafterDirectoryListEntry.xml' the '04/04/2012 14:27:37'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class JobCrafterDirectoryListEntry
	{
		public const uint Id = 196;
		public virtual short TypeId
		{
			get
			{
				return 196;
			}
		}
		
		public Types.JobCrafterDirectoryEntryPlayerInfo playerInfo;
		public Types.JobCrafterDirectoryEntryJobInfo jobInfo;
		
		public JobCrafterDirectoryListEntry()
		{
		}
		
		public JobCrafterDirectoryListEntry(Types.JobCrafterDirectoryEntryPlayerInfo playerInfo, Types.JobCrafterDirectoryEntryJobInfo jobInfo)
		{
			this.playerInfo = playerInfo;
			this.jobInfo = jobInfo;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			playerInfo.Serialize(writer);
			jobInfo.Serialize(writer);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			playerInfo = new Types.JobCrafterDirectoryEntryPlayerInfo();
			playerInfo.Deserialize(reader);
			jobInfo = new Types.JobCrafterDirectoryEntryJobInfo();
			jobInfo.Deserialize(reader);
		}
	}
}
