// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'EntityTalkMessage.xml' the '04/04/2012 14:27:28'
using System;
using Stump.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace Stump.DofusProtocol.Messages
{
	public class EntityTalkMessage : Message
	{
		public const uint Id = 6110;
		public override uint MessageId
		{
			get
			{
				return 6110;
			}
		}
		
		public int entityId;
		public short textId;
		public IEnumerable<string> parameters;
		
		public EntityTalkMessage()
		{
		}
		
		public EntityTalkMessage(int entityId, short textId, IEnumerable<string> parameters)
		{
			this.entityId = entityId;
			this.textId = textId;
			this.parameters = parameters;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(entityId);
			writer.WriteShort(textId);
			writer.WriteUShort((ushort)parameters.Count());
			foreach (var entry in parameters)
			{
				writer.WriteUTF(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			entityId = reader.ReadInt();
			textId = reader.ReadShort();
			if ( textId < 0 )
			{
				throw new Exception("Forbidden value on textId = " + textId + ", it doesn't respect the following condition : textId < 0");
			}
			int limit = reader.ReadUShort();
			parameters = new string[limit];
			for (int i = 0; i < limit; i++)
			{
				(parameters as string[])[i] = reader.ReadUTF();
			}
		}
	}
}
