// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TeleportBuddiesMessage.xml' the '04/04/2012 14:27:32'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class TeleportBuddiesMessage : Message
	{
		public const uint Id = 6289;
		public override uint MessageId
		{
			get
			{
				return 6289;
			}
		}
		
		public short dungeonId;
		
		public TeleportBuddiesMessage()
		{
		}
		
		public TeleportBuddiesMessage(short dungeonId)
		{
			this.dungeonId = dungeonId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteShort(dungeonId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			dungeonId = reader.ReadShort();
			if ( dungeonId < 0 )
			{
				throw new Exception("Forbidden value on dungeonId = " + dungeonId + ", it doesn't respect the following condition : dungeonId < 0");
			}
		}
	}
}
