// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'NetworkDataContainerMessage.xml' the '04/04/2012 14:27:18'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class NetworkDataContainerMessage : Message
	{
		public const uint Id = 2;
		public override uint MessageId
		{
			get
			{
				return 2;
			}
		}
		
		
		public override void Serialize(IDataWriter writer)
		{
		}
		
		public override void Deserialize(IDataReader reader)
		{
		}
	}
}
