// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameActionFightUnmarkCellsMessage.xml' the '04/04/2012 14:27:20'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GameActionFightUnmarkCellsMessage : AbstractGameActionMessage
	{
		public const uint Id = 5570;
		public override uint MessageId
		{
			get
			{
				return 5570;
			}
		}
		
		public short markId;
		
		public GameActionFightUnmarkCellsMessage()
		{
		}
		
		public GameActionFightUnmarkCellsMessage(short actionId, int sourceId, short markId)
			 : base(actionId, sourceId)
		{
			this.markId = markId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteShort(markId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			markId = reader.ReadShort();
		}
	}
}
