// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeRequestMessage.xml' the '04/04/2012 14:27:33'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeRequestMessage : Message
	{
		public const uint Id = 5505;
		public override uint MessageId
		{
			get
			{
				return 5505;
			}
		}
		
		public sbyte exchangeType;
		
		public ExchangeRequestMessage()
		{
		}
		
		public ExchangeRequestMessage(sbyte exchangeType)
		{
			this.exchangeType = exchangeType;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(exchangeType);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			exchangeType = reader.ReadSByte();
		}
	}
}
