// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeErrorMessage.xml' the '04/04/2012 14:27:32'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeErrorMessage : Message
	{
		public const uint Id = 5513;
		public override uint MessageId
		{
			get
			{
				return 5513;
			}
		}
		
		public sbyte errorType;
		
		public ExchangeErrorMessage()
		{
		}
		
		public ExchangeErrorMessage(sbyte errorType)
		{
			this.errorType = errorType;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(errorType);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			errorType = reader.ReadSByte();
		}
	}
}
