// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeShopStockMultiMovementRemovedMessage.xml' the '04/04/2012 14:27:33'
using System;
using Stump.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeShopStockMultiMovementRemovedMessage : Message
	{
		public const uint Id = 6037;
		public override uint MessageId
		{
			get
			{
				return 6037;
			}
		}
		
		public IEnumerable<int> objectIdList;
		
		public ExchangeShopStockMultiMovementRemovedMessage()
		{
		}
		
		public ExchangeShopStockMultiMovementRemovedMessage(IEnumerable<int> objectIdList)
		{
			this.objectIdList = objectIdList;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)objectIdList.Count());
			foreach (var entry in objectIdList)
			{
				writer.WriteInt(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			objectIdList = new int[limit];
			for (int i = 0; i < limit; i++)
			{
				(objectIdList as int[])[i] = reader.ReadInt();
			}
		}
	}
}
