// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeCraftInformationObjectMessage.xml' the '04/04/2012 14:27:32'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeCraftInformationObjectMessage : ExchangeCraftResultWithObjectIdMessage
	{
		public const uint Id = 5794;
		public override uint MessageId
		{
			get
			{
				return 5794;
			}
		}
		
		public int playerId;
		
		public ExchangeCraftInformationObjectMessage()
		{
		}
		
		public ExchangeCraftInformationObjectMessage(sbyte craftResult, int objectGenericId, int playerId)
			 : base(craftResult, objectGenericId)
		{
			this.playerId = playerId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(playerId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			playerId = reader.ReadInt();
			if ( playerId < 0 )
			{
				throw new Exception("Forbidden value on playerId = " + playerId + ", it doesn't respect the following condition : playerId < 0");
			}
		}
	}
}
