// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeStartOkCraftWithInformationMessage.xml' the '04/04/2012 14:27:34'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeStartOkCraftWithInformationMessage : ExchangeStartOkCraftMessage
	{
		public const uint Id = 5941;
		public override uint MessageId
		{
			get
			{
				return 5941;
			}
		}
		
		public sbyte nbCase;
		public int skillId;
		
		public ExchangeStartOkCraftWithInformationMessage()
		{
		}
		
		public ExchangeStartOkCraftWithInformationMessage(sbyte nbCase, int skillId)
		{
			this.nbCase = nbCase;
			this.skillId = skillId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteSByte(nbCase);
			writer.WriteInt(skillId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			nbCase = reader.ReadSByte();
			if ( nbCase < 0 )
			{
				throw new Exception("Forbidden value on nbCase = " + nbCase + ", it doesn't respect the following condition : nbCase < 0");
			}
			skillId = reader.ReadInt();
			if ( skillId < 0 )
			{
				throw new Exception("Forbidden value on skillId = " + skillId + ", it doesn't respect the following condition : skillId < 0");
			}
		}
	}
}
