// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeCraftResultMessage.xml' the '04/04/2012 14:27:32'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeCraftResultMessage : Message
	{
		public const uint Id = 5790;
		public override uint MessageId
		{
			get
			{
				return 5790;
			}
		}
		
		public sbyte craftResult;
		
		public ExchangeCraftResultMessage()
		{
		}
		
		public ExchangeCraftResultMessage(sbyte craftResult)
		{
			this.craftResult = craftResult;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(craftResult);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			craftResult = reader.ReadSByte();
			if ( craftResult < 0 )
			{
				throw new Exception("Forbidden value on craftResult = " + craftResult + ", it doesn't respect the following condition : craftResult < 0");
			}
		}
	}
}
