// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeWaitingResultMessage.xml' the '04/04/2012 14:27:34'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeWaitingResultMessage : Message
	{
		public const uint Id = 5786;
		public override uint MessageId
		{
			get
			{
				return 5786;
			}
		}
		
		public bool bwait;
		
		public ExchangeWaitingResultMessage()
		{
		}
		
		public ExchangeWaitingResultMessage(bool bwait)
		{
			this.bwait = bwait;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(bwait);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			bwait = reader.ReadBoolean();
		}
	}
}
