// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeStartOkJobIndexMessage.xml' the '04/04/2012 14:27:34'
using System;
using Stump.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeStartOkJobIndexMessage : Message
	{
		public const uint Id = 5819;
		public override uint MessageId
		{
			get
			{
				return 5819;
			}
		}
		
		public IEnumerable<int> jobs;
		
		public ExchangeStartOkJobIndexMessage()
		{
		}
		
		public ExchangeStartOkJobIndexMessage(IEnumerable<int> jobs)
		{
			this.jobs = jobs;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)jobs.Count());
			foreach (var entry in jobs)
			{
				writer.WriteInt(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			jobs = new int[limit];
			for (int i = 0; i < limit; i++)
			{
				(jobs as int[])[i] = reader.ReadInt();
			}
		}
	}
}
