// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeRequestOnTaxCollectorMessage.xml' the '04/04/2012 14:27:33'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeRequestOnTaxCollectorMessage : Message
	{
		public const uint Id = 5779;
		public override uint MessageId
		{
			get
			{
				return 5779;
			}
		}
		
		public int taxCollectorId;
		
		public ExchangeRequestOnTaxCollectorMessage()
		{
		}
		
		public ExchangeRequestOnTaxCollectorMessage(int taxCollectorId)
		{
			this.taxCollectorId = taxCollectorId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(taxCollectorId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			taxCollectorId = reader.ReadInt();
		}
	}
}
