// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeReplayCountModifiedMessage.xml' the '04/04/2012 14:27:33'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeReplayCountModifiedMessage : Message
	{
		public const uint Id = 6023;
		public override uint MessageId
		{
			get
			{
				return 6023;
			}
		}
		
		public int count;
		
		public ExchangeReplayCountModifiedMessage()
		{
		}
		
		public ExchangeReplayCountModifiedMessage(int count)
		{
			this.count = count;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(count);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			count = reader.ReadInt();
		}
	}
}
