// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeObjectTransfertListFromInvMessage.xml' the '04/04/2012 14:27:33'
using System;
using Stump.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeObjectTransfertListFromInvMessage : Message
	{
		public const uint Id = 6183;
		public override uint MessageId
		{
			get
			{
				return 6183;
			}
		}
		
		public IEnumerable<int> ids;
		
		public ExchangeObjectTransfertListFromInvMessage()
		{
		}
		
		public ExchangeObjectTransfertListFromInvMessage(IEnumerable<int> ids)
		{
			this.ids = ids;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)ids.Count());
			foreach (var entry in ids)
			{
				writer.WriteInt(entry);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			ids = new int[limit];
			for (int i = 0; i < limit; i++)
			{
				(ids as int[])[i] = reader.ReadInt();
			}
		}
	}
}
