// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ExchangeBidHouseBuyResultMessage.xml' the '04/04/2012 14:27:32'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class ExchangeBidHouseBuyResultMessage : Message
	{
		public const uint Id = 6272;
		public override uint MessageId
		{
			get
			{
				return 6272;
			}
		}
		
		public int uid;
		public bool bought;
		
		public ExchangeBidHouseBuyResultMessage()
		{
		}
		
		public ExchangeBidHouseBuyResultMessage(int uid, bool bought)
		{
			this.uid = uid;
			this.bought = bought;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(uid);
			writer.WriteBoolean(bought);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			uid = reader.ReadInt();
			if ( uid < 0 )
			{
				throw new Exception("Forbidden value on uid = " + uid + ", it doesn't respect the following condition : uid < 0");
			}
			bought = reader.ReadBoolean();
		}
	}
}
