// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'HouseGuildRightsMessage.xml' the '04/04/2012 14:27:26'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class HouseGuildRightsMessage : Message
	{
		public const uint Id = 5703;
		public override uint MessageId
		{
			get
			{
				return 5703;
			}
		}
		
		public short houseId;
		public Types.GuildInformations guildInfo;
		public uint rights;
		
		public HouseGuildRightsMessage()
		{
		}
		
		public HouseGuildRightsMessage(short houseId, Types.GuildInformations guildInfo, uint rights)
		{
			this.houseId = houseId;
			this.guildInfo = guildInfo;
			this.rights = rights;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteShort(houseId);
			guildInfo.Serialize(writer);
			writer.WriteUInt(rights);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			houseId = reader.ReadShort();
			if ( houseId < 0 )
			{
				throw new Exception("Forbidden value on houseId = " + houseId + ", it doesn't respect the following condition : houseId < 0");
			}
			guildInfo = new Types.GuildInformations();
			guildInfo.Deserialize(reader);
			rights = reader.ReadUInt();
			if ( rights < 0 || rights > 4294967295 )
			{
				throw new Exception("Forbidden value on rights = " + rights + ", it doesn't respect the following condition : rights < 0 || rights > 4294967295");
			}
		}
	}
}
