// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ObjectItemInformationWithQuantity.xml' the '04/04/2012 14:27:38'
using System;
using Stump.Core.IO;
using System.Collections.Generic;

namespace Stump.DofusProtocol.Types
{
	public class ObjectItemInformationWithQuantity : ObjectItemMinimalInformation
	{
		public const uint Id = 387;
		public override short TypeId
		{
			get
			{
				return 387;
			}
		}
		
		public int quantity;
		
		public ObjectItemInformationWithQuantity()
		{
		}
		
		public ObjectItemInformationWithQuantity(short objectGID, short powerRate, bool overMax, IEnumerable<Types.ObjectEffect> effects, int quantity)
			 : base(objectGID, powerRate, overMax, effects)
		{
			this.quantity = quantity;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(quantity);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			quantity = reader.ReadInt();
			if ( quantity < 0 )
			{
				throw new Exception("Forbidden value on quantity = " + quantity + ", it doesn't respect the following condition : quantity < 0");
			}
		}
	}
}
