// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'HousePropertiesMessage.xml' the '04/04/2012 14:27:26'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class HousePropertiesMessage : Message
	{
		public const uint Id = 5734;
		public override uint MessageId
		{
			get
			{
				return 5734;
			}
		}
		
		public Types.HouseInformations properties;
		
		public HousePropertiesMessage()
		{
		}
		
		public HousePropertiesMessage(Types.HouseInformations properties)
		{
			this.properties = properties;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteShort(properties.TypeId);
			properties.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			properties = Types.ProtocolTypeManager.GetInstance<Types.HouseInformations>(reader.ReadShort());
			properties.Deserialize(reader);
		}
	}
}
