// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'AlignmentSideEnum.as' the '04/04/2012 14:27:39'

namespace Stump.DofusProtocol.Enums
{
	public enum AlignmentSideEnum
	{
		ALIGNMENT_UNKNOWN = -2,
		ALIGNMENT_WITHOUT = -1,
		ALIGNMENT_NEUTRAL = 0,
		ALIGNMENT_ANGEL = 1,
		ALIGNMENT_EVIL = 2,
		ALIGNMENT_MERCENARY = 3,
	}
}
