// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CharacterCreationResultEnum.as' the '04/04/2012 14:27:39'

namespace Stump.DofusProtocol.Enums
{
	public enum CharacterCreationResultEnum
	{
		OK = 0,
		ERR_NO_REASON = 1,
		ERR_INVALID_NAME = 2,
		ERR_NAME_ALREADY_EXISTS = 3,
		ERR_TOO_MANY_CHARACTERS = 4,
		ERR_NOT_ALLOWED = 5,
		ERR_NEW_PLAYER_NOT_ALLOWED = 6,
		ERR_RESTRICED_ZONE = 7,
	}
}
