// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'CharacterDeletionErrorEnum.as' the '04/04/2012 14:27:39'

namespace Stump.DofusProtocol.Enums
{
	public enum CharacterDeletionErrorEnum
	{
		DEL_ERR_NO_REASON = 1,
		DEL_ERR_TOO_MANY_CHAR_DELETION = 2,
		DEL_ERR_BAD_SECRET_ANSWER = 3,
		DEL_ERR_RESTRICED_ZONE = 4,
	}
}
