// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightDispellableEnum.as' the '04/04/2012 14:27:39'

namespace Stump.DofusProtocol.Enums
{
	public enum FightDispellableEnum
	{
		DISPELLABLE = 1,
		DISPELLABLE_BY_DEATH = 2,
		NOT_DISPELLABLE = 3,
	}
}
