// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightOptionsEnum.as' the '04/04/2012 14:27:39'

namespace Stump.DofusProtocol.Enums
{
	public enum FightOptionsEnum
	{
		FIGHT_OPTION_SET_SECRET = 0,
		FIGHT_OPTION_SET_TO_PARTY_ONLY = 1,
		FIGHT_OPTION_SET_CLOSED = 2,
		FIGHT_OPTION_ASK_FOR_HELP = 3,
	}
}
