// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightSpellCastCriticalEnum.as' the '04/04/2012 14:27:39'

namespace Stump.DofusProtocol.Enums
{
	public enum FightSpellCastCriticalEnum
	{
		NORMAL = 1,
		CRITICAL_HIT = 2,
		CRITICAL_FAIL = 3,
	}
}
