// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameActionMarkCellsTypeEnum.as' the '04/04/2012 14:27:39'

namespace Stump.DofusProtocol.Enums
{
	public enum GameActionMarkCellsTypeEnum
	{
		CELLS_CIRCLE = 0,
		CELLS_CROSS = 1,
	}
}
