// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuildInformationsTypeEnum.as' the '04/04/2012 14:27:39'

namespace Stump.DofusProtocol.Enums
{
	public enum GuildInformationsTypeEnum
	{
		INFO_GENERAL = 1,
		INFO_MEMBERS = 2,
		INFO_BOOSTS = 3,
		INFO_PADDOCKS = 4,
		INFO_HOUSES = 5,
		INFO_TAX_COLLECTOR = 6,
		INFO_TAX_COLLECTOR_LEAVE = 7,
	}
}
