// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GuildInvitationStateEnum.as' the '04/04/2012 14:27:39'

namespace Stump.DofusProtocol.Enums
{
	public enum GuildInvitationStateEnum
	{
		GUILD_INVITATION_SENT = 1,
		GUILD_INVITATION_CANCELED = 2,
		GUILD_INVITATION_OK = 3,
	}
}
