// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'HardcoreDeathStateEnum.as' the '04/04/2012 14:27:39'

namespace Stump.DofusProtocol.Enums
{
	public enum HardcoreDeathStateEnum
	{
		DEATH_STATE_ALIVE = 0,
		DEATH_STATE_DEAD = 1,
		DEATH_STATE_WAITING_CONFIRMATION = 2,
	}
}
