// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'IdentificationFailureReasonEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum IdentificationFailureReasonEnum
	{
		BAD_VERSION = 1,
		WRONG_CREDENTIALS = 2,
		BANNED = 3,
		KICKED = 4,
		IN_MAINTENANCE = 5,
		TOO_MANY_ON_IP = 6,
		TIME_OUT = 7,
		BAD_IPRANGE = 8,
		CREDENTIALS_RESET = 9,
		EMAIL_UNVALIDATED = 10,
		UNKNOWN_AUTH_ERROR = 99,
		SPARE = 100,
	}
}
