// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ListAddFailureEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum ListAddFailureEnum
	{
		LIST_ADD_FAILURE_UNKNOWN = 0,
		LIST_ADD_FAILURE_OVER_QUOTA = 1,
		LIST_ADD_FAILURE_NOT_FOUND = 2,
		LIST_ADD_FAILURE_EGOCENTRIC = 3,
		LIST_ADD_FAILURE_IS_DOUBLE = 4,
	}
}
