// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MapObstacleStateEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum MapObstacleStateEnum
	{
		OBSTACLE_OPENED = 1,
		OBSTACLE_CLOSED = 2,
	}
}
