// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MountEquipedErrorEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum MountEquipedErrorEnum
	{
		UNSET = 0,
		SET = 1,
		RIDING = 2,
	}
}
