// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'NicknameGeneratingFailureEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum NicknameGeneratingFailureEnum
	{
		NICKNAME_GENERATOR_RETRY_TOO_SHORT = 1,
		NICKNAME_GENERATOR_UNAVAILABLE = 2,
	}
}
