// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartyTypeEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum PartyTypeEnum
	{
		PARTY_TYPE_UNDEFINED = 0,
		PARTY_TYPE_CLASSICAL = 1,
		PARTY_TYPE_DUNGEON = 2,
		PARTY_TYPE_ARENA = 3,
	}
}
