// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartStateEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum PartStateEnum
	{
		PART_NOT_INSTALLED = 0,
		PART_BEING_UPDATER = 1,
		PART_UP_TO_DATE = 2,
	}
}
