// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PaymentTypeEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum PaymentTypeEnum
	{
		PAYMENT_ON_SUCCESS_ONLY = 0,
		PAYMENT_IN_ANY_CASE = 1,
	}
}
