// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PlayerLifeStatusEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum PlayerLifeStatusEnum
	{
		STATUS_ALIVE_AND_KICKING = 0,
		STATUS_TOMBSTONE = 1,
		STATUS_PHANTOM = 2,
	}
}
