// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PresetSaveUpdateErrorEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum PresetSaveUpdateErrorEnum
	{
		PRESET_UPDATE_ERR_UNKNOWN = 1,
		PRESET_UPDATE_ERR_BAD_PRESET_ID = 2,
		PRESET_UPDATE_ERR_BAD_POSITION = 3,
		PRESET_UPDATE_ERR_BAD_OBJECT_ID = 4,
	}
}
