// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PvpArenaStepEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum PvpArenaStepEnum
	{
		ARENA_STEP_REGISTRED = 0,
		ARENA_STEP_WAITING_FIGHT = 1,
		ARENA_STEP_STARTING_FIGHT = 2,
		ARENA_STEP_UNREGISTER = 3,
	}
}
