// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PvpArenaTypeEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum PvpArenaTypeEnum
	{
		ARENA_TYPE_3VS3 = 3,
		ARENA_TYPE_5VS5 = 5,
	}
}
