// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ServerStatusEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum ServerStatusEnum
	{
		STATUS_UNKNOWN = 0,
		OFFLINE = 1,
		STARTING = 2,
		ONLINE = 3,
		NOJOIN = 4,
		SAVING = 5,
		STOPING = 6,
		FULL = 7,
	}
}
