// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ShortcutBarEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum ShortcutBarEnum
	{
		GENERAL_SHORTCUT_BAR = 0,
		SPELL_SHORTCUT_BAR = 1,
	}
}
