// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'SubscriptionRequiredEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum SubscriptionRequiredEnum
	{
		LIMITED_TO_SUBSCRIBER = 0,
		LIMIT_ON_JOB_XP = 1,
		LIMIT_ON_JOB_USE = 2,
		LIMIT_ON_MAP = 3,
		LIMIT_ON_ITEM = 4,
		LIMIT_ON_VENDOR = 5,
	}
}
