// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TeamEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum TeamEnum
	{
		TEAM_CHALLENGER = 0,
		TEAM_DEFENDER = 1,
		TEAM_SPECTATOR = 2,
	}
}
