// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TeleporterTypeEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum TeleporterTypeEnum
	{
		TELEPORTER_ZAAP = 0,
		TELEPORTER_SUBWAY = 1,
		TELEPORTER_PRISM = 2,
	}
}
