// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TextInformationTypeEnum.as' the '04/04/2012 14:27:40'

namespace Stump.DofusProtocol.Enums
{
	public enum TextInformationTypeEnum
	{
		TEXT_INFORMATION_MESSAGE = 0,
		TEXT_INFORMATION_ERROR = 1,
		TEXT_INFORMATION_PVP = 2,
		TEXT_INFORMATION_FIGHT_LOG = 3,
		TEXT_INFORMATION_POPUP = 4,
		TEXT_LIVING_OBJECT = 5,
		TEXT_ENTITY_TALK = 6,
		TEXT_INFORMATION_FIGHT = 7,
	}
}
