// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'EmotePlayAbstractMessage.xml' the '04/04/2012 14:27:25'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class EmotePlayAbstractMessage : Message
	{
		public const uint Id = 5690;
		public override uint MessageId
		{
			get
			{
				return 5690;
			}
		}
		
		public sbyte emoteId;
		public double emoteStartTime;
		
		public EmotePlayAbstractMessage()
		{
		}
		
		public EmotePlayAbstractMessage(sbyte emoteId, double emoteStartTime)
		{
			this.emoteId = emoteId;
			this.emoteStartTime = emoteStartTime;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(emoteId);
			writer.WriteDouble(emoteStartTime);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			emoteId = reader.ReadSByte();
			if ( emoteId < 0 )
			{
				throw new Exception("Forbidden value on emoteId = " + emoteId + ", it doesn't respect the following condition : emoteId < 0");
			}
			emoteStartTime = reader.ReadDouble();
		}
	}
}
