// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'EmoteAddMessage.xml' the '04/04/2012 14:27:25'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class EmoteAddMessage : Message
	{
		public const uint Id = 5644;
		public override uint MessageId
		{
			get
			{
				return 5644;
			}
		}
		
		public sbyte emoteId;
		
		public EmoteAddMessage()
		{
		}
		
		public EmoteAddMessage(sbyte emoteId)
		{
			this.emoteId = emoteId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(emoteId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			emoteId = reader.ReadSByte();
			if ( emoteId < 0 )
			{
				throw new Exception("Forbidden value on emoteId = " + emoteId + ", it doesn't respect the following condition : emoteId < 0");
			}
		}
	}
}
