// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'StorageKamasUpdateMessage.xml' the '04/04/2012 14:27:35'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class StorageKamasUpdateMessage : Message
	{
		public const uint Id = 5645;
		public override uint MessageId
		{
			get
			{
				return 5645;
			}
		}
		
		public int kamasTotal;
		
		public StorageKamasUpdateMessage()
		{
		}
		
		public StorageKamasUpdateMessage(int kamasTotal)
		{
			this.kamasTotal = kamasTotal;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(kamasTotal);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			kamasTotal = reader.ReadInt();
		}
	}
}
