// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ObjectEffectDice.xml' the '04/04/2012 14:27:38'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class ObjectEffectDice : ObjectEffect
	{
		public const uint Id = 73;
		public override short TypeId
		{
			get
			{
				return 73;
			}
		}
		
		public short diceNum;
		public short diceSide;
		public short diceConst;
		
		public ObjectEffectDice()
		{
		}
		
		public ObjectEffectDice(short actionId, short diceNum, short diceSide, short diceConst)
			 : base(actionId)
		{
			this.diceNum = diceNum;
			this.diceSide = diceSide;
			this.diceConst = diceConst;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteShort(diceNum);
			writer.WriteShort(diceSide);
			writer.WriteShort(diceConst);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			diceNum = reader.ReadShort();
			if ( diceNum < 0 )
			{
				throw new Exception("Forbidden value on diceNum = " + diceNum + ", it doesn't respect the following condition : diceNum < 0");
			}
			diceSide = reader.ReadShort();
			if ( diceSide < 0 )
			{
				throw new Exception("Forbidden value on diceSide = " + diceSide + ", it doesn't respect the following condition : diceSide < 0");
			}
			diceConst = reader.ReadShort();
			if ( diceConst < 0 )
			{
				throw new Exception("Forbidden value on diceConst = " + diceConst + ", it doesn't respect the following condition : diceConst < 0");
			}
		}
	}
}
