// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'IgnoredInformations.xml' the '04/04/2012 14:27:38'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class IgnoredInformations : AbstractContactInformations
	{
		public const uint Id = 106;
		public override short TypeId
		{
			get
			{
				return 106;
			}
		}
		
		
		public IgnoredInformations()
		{
		}
		
		public IgnoredInformations(int accountId, string accountName)
			 : base(accountId, accountName)
		{
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
		}
	}
}
