// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'StatedElement.xml' the '04/04/2012 14:27:39'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class StatedElement
	{
		public const uint Id = 108;
		public virtual short TypeId
		{
			get
			{
				return 108;
			}
		}
		
		public int elementId;
		public short elementCellId;
		public int elementState;
		
		public StatedElement()
		{
		}
		
		public StatedElement(int elementId, short elementCellId, int elementState)
		{
			this.elementId = elementId;
			this.elementCellId = elementCellId;
			this.elementState = elementState;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteInt(elementId);
			writer.WriteShort(elementCellId);
			writer.WriteInt(elementState);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			elementId = reader.ReadInt();
			if ( elementId < 0 )
			{
				throw new Exception("Forbidden value on elementId = " + elementId + ", it doesn't respect the following condition : elementId < 0");
			}
			elementCellId = reader.ReadShort();
			if ( elementCellId < 0 || elementCellId > 559 )
			{
				throw new Exception("Forbidden value on elementCellId = " + elementCellId + ", it doesn't respect the following condition : elementCellId < 0 || elementCellId > 559");
			}
			elementState = reader.ReadInt();
			if ( elementState < 0 )
			{
				throw new Exception("Forbidden value on elementState = " + elementState + ", it doesn't respect the following condition : elementState < 0");
			}
		}
	}
}
