// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameRolePlayArenaFightAnswerMessage.xml' the '04/04/2012 14:27:26'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GameRolePlayArenaFightAnswerMessage : Message
	{
		public const uint Id = 6279;
		public override uint MessageId
		{
			get
			{
				return 6279;
			}
		}
		
		public int fightId;
		public bool accept;
		
		public GameRolePlayArenaFightAnswerMessage()
		{
		}
		
		public GameRolePlayArenaFightAnswerMessage(int fightId, bool accept)
		{
			this.fightId = fightId;
			this.accept = accept;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(fightId);
			writer.WriteBoolean(accept);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			fightId = reader.ReadInt();
			accept = reader.ReadBoolean();
		}
	}
}
