// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'JobAllowMultiCraftRequestSetMessage.xml' the '04/04/2012 14:27:27'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class JobAllowMultiCraftRequestSetMessage : Message
	{
		public const uint Id = 5749;
		public override uint MessageId
		{
			get
			{
				return 5749;
			}
		}
		
		public bool enabled;
		
		public JobAllowMultiCraftRequestSetMessage()
		{
		}
		
		public JobAllowMultiCraftRequestSetMessage(bool enabled)
		{
			this.enabled = enabled;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(enabled);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			enabled = reader.ReadBoolean();
		}
	}
}
