// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'JobCrafterDirectoryEntryRequestMessage.xml' the '04/04/2012 14:27:27'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class JobCrafterDirectoryEntryRequestMessage : Message
	{
		public const uint Id = 6043;
		public override uint MessageId
		{
			get
			{
				return 6043;
			}
		}
		
		public int playerId;
		
		public JobCrafterDirectoryEntryRequestMessage()
		{
		}
		
		public JobCrafterDirectoryEntryRequestMessage(int playerId)
		{
			this.playerId = playerId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(playerId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			playerId = reader.ReadInt();
			if ( playerId < 0 )
			{
				throw new Exception("Forbidden value on playerId = " + playerId + ", it doesn't respect the following condition : playerId < 0");
			}
		}
	}
}
