// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'JobExperienceMultiUpdateMessage.xml' the '04/04/2012 14:27:27'
using System;
using Stump.Core.IO;
using System.Collections.Generic;
using System.Linq;

namespace Stump.DofusProtocol.Messages
{
	public class JobExperienceMultiUpdateMessage : Message
	{
		public const uint Id = 5809;
		public override uint MessageId
		{
			get
			{
				return 5809;
			}
		}
		
		public IEnumerable<Types.JobExperience> experiencesUpdate;
		
		public JobExperienceMultiUpdateMessage()
		{
		}
		
		public JobExperienceMultiUpdateMessage(IEnumerable<Types.JobExperience> experiencesUpdate)
		{
			this.experiencesUpdate = experiencesUpdate;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteUShort((ushort)experiencesUpdate.Count());
			foreach (var entry in experiencesUpdate)
			{
				entry.Serialize(writer);
			}
		}
		
		public override void Deserialize(IDataReader reader)
		{
			int limit = reader.ReadUShort();
			experiencesUpdate = new Types.JobExperience[limit];
			for (int i = 0; i < limit; i++)
			{
				(experiencesUpdate as Types.JobExperience[])[i] = new Types.JobExperience();
				(experiencesUpdate as Types.JobExperience[])[i].Deserialize(reader);
			}
		}
	}
}
