// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'JobLevelUpMessage.xml' the '04/04/2012 14:27:27'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class JobLevelUpMessage : Message
	{
		public const uint Id = 5656;
		public override uint MessageId
		{
			get
			{
				return 5656;
			}
		}
		
		public sbyte newLevel;
		public Types.JobDescription jobsDescription;
		
		public JobLevelUpMessage()
		{
		}
		
		public JobLevelUpMessage(sbyte newLevel, Types.JobDescription jobsDescription)
		{
			this.newLevel = newLevel;
			this.jobsDescription = jobsDescription;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(newLevel);
			jobsDescription.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			newLevel = reader.ReadSByte();
			if ( newLevel < 0 )
			{
				throw new Exception("Forbidden value on newLevel = " + newLevel + ", it doesn't respect the following condition : newLevel < 0");
			}
			jobsDescription = new Types.JobDescription();
			jobsDescription.Deserialize(reader);
		}
	}
}
