// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'SubEntity.xml' the '04/04/2012 14:27:39'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class SubEntity
	{
		public const uint Id = 54;
		public virtual short TypeId
		{
			get
			{
				return 54;
			}
		}
		
		public sbyte bindingPointCategory;
		public sbyte bindingPointIndex;
		public Types.EntityLook subEntityLook;
		
		public SubEntity()
		{
		}
		
		public SubEntity(sbyte bindingPointCategory, sbyte bindingPointIndex, Types.EntityLook subEntityLook)
		{
			this.bindingPointCategory = bindingPointCategory;
			this.bindingPointIndex = bindingPointIndex;
			this.subEntityLook = subEntityLook;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(bindingPointCategory);
			writer.WriteSByte(bindingPointIndex);
			subEntityLook.Serialize(writer);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			bindingPointCategory = reader.ReadSByte();
			if ( bindingPointCategory < 0 )
			{
				throw new Exception("Forbidden value on bindingPointCategory = " + bindingPointCategory + ", it doesn't respect the following condition : bindingPointCategory < 0");
			}
			bindingPointIndex = reader.ReadSByte();
			if ( bindingPointIndex < 0 )
			{
				throw new Exception("Forbidden value on bindingPointIndex = " + bindingPointIndex + ", it doesn't respect the following condition : bindingPointIndex < 0");
			}
			subEntityLook = new Types.EntityLook();
			subEntityLook.Deserialize(reader);
		}
	}
}
