// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'MapCoordinatesExtended.xml' the '04/04/2012 14:27:37'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class MapCoordinatesExtended : MapCoordinatesAndId
	{
		public const uint Id = 176;
		public override short TypeId
		{
			get
			{
				return 176;
			}
		}
		
		public short subAreaId;
		
		public MapCoordinatesExtended()
		{
		}
		
		public MapCoordinatesExtended(short worldX, short worldY, int mapId, short subAreaId)
			 : base(worldX, worldY, mapId)
		{
			this.subAreaId = subAreaId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteShort(subAreaId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			subAreaId = reader.ReadShort();
			if ( subAreaId < 0 )
			{
				throw new Exception("Forbidden value on subAreaId = " + subAreaId + ", it doesn't respect the following condition : subAreaId < 0");
			}
		}
	}
}
