// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PaddockSellBuyDialogMessage.xml' the '04/04/2012 14:27:28'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class PaddockSellBuyDialogMessage : Message
	{
		public const uint Id = 6018;
		public override uint MessageId
		{
			get
			{
				return 6018;
			}
		}
		
		public bool bsell;
		public int ownerId;
		public int price;
		
		public PaddockSellBuyDialogMessage()
		{
		}
		
		public PaddockSellBuyDialogMessage(bool bsell, int ownerId, int price)
		{
			this.bsell = bsell;
			this.ownerId = ownerId;
			this.price = price;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteBoolean(bsell);
			writer.WriteInt(ownerId);
			writer.WriteInt(price);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			bsell = reader.ReadBoolean();
			ownerId = reader.ReadInt();
			if ( ownerId < 0 )
			{
				throw new Exception("Forbidden value on ownerId = " + ownerId + ", it doesn't respect the following condition : ownerId < 0");
			}
			price = reader.ReadInt();
			if ( price < 0 )
			{
				throw new Exception("Forbidden value on price = " + price + ", it doesn't respect the following condition : price < 0");
			}
		}
	}
}
