// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PaddockToSellFilterMessage.xml' the '04/04/2012 14:27:28'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class PaddockToSellFilterMessage : Message
	{
		public const uint Id = 6161;
		public override uint MessageId
		{
			get
			{
				return 6161;
			}
		}
		
		public int areaId;
		public sbyte atLeastNbMount;
		public sbyte atLeastNbMachine;
		public int maxPrice;
		
		public PaddockToSellFilterMessage()
		{
		}
		
		public PaddockToSellFilterMessage(int areaId, sbyte atLeastNbMount, sbyte atLeastNbMachine, int maxPrice)
		{
			this.areaId = areaId;
			this.atLeastNbMount = atLeastNbMount;
			this.atLeastNbMachine = atLeastNbMachine;
			this.maxPrice = maxPrice;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(areaId);
			writer.WriteSByte(atLeastNbMount);
			writer.WriteSByte(atLeastNbMachine);
			writer.WriteInt(maxPrice);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			areaId = reader.ReadInt();
			atLeastNbMount = reader.ReadSByte();
			atLeastNbMachine = reader.ReadSByte();
			maxPrice = reader.ReadInt();
			if ( maxPrice < 0 )
			{
				throw new Exception("Forbidden value on maxPrice = " + maxPrice + ", it doesn't respect the following condition : maxPrice < 0");
			}
		}
	}
}
