// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'ItemDurability.xml' the '04/04/2012 14:27:39'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class ItemDurability
	{
		public const uint Id = 168;
		public virtual short TypeId
		{
			get
			{
				return 168;
			}
		}
		
		public short durability;
		public short durabilityMax;
		
		public ItemDurability()
		{
		}
		
		public ItemDurability(short durability, short durabilityMax)
		{
			this.durability = durability;
			this.durabilityMax = durabilityMax;
		}
		
		public virtual void Serialize(IDataWriter writer)
		{
			writer.WriteShort(durability);
			writer.WriteShort(durabilityMax);
		}
		
		public virtual void Deserialize(IDataReader reader)
		{
			durability = reader.ReadShort();
			durabilityMax = reader.ReadShort();
		}
	}
}
