// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartyInvitationCancelledForGuestMessage.xml' the '04/04/2012 14:27:29'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class PartyInvitationCancelledForGuestMessage : AbstractPartyMessage
	{
		public const uint Id = 6256;
		public override uint MessageId
		{
			get
			{
				return 6256;
			}
		}
		
		public int cancelerId;
		
		public PartyInvitationCancelledForGuestMessage()
		{
		}
		
		public PartyInvitationCancelledForGuestMessage(int partyId, int cancelerId)
			 : base(partyId)
		{
			this.cancelerId = cancelerId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(cancelerId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			cancelerId = reader.ReadInt();
			if ( cancelerId < 0 )
			{
				throw new Exception("Forbidden value on cancelerId = " + cancelerId + ", it doesn't respect the following condition : cancelerId < 0");
			}
		}
	}
}
