// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'PartyKickedByMessage.xml' the '04/04/2012 14:27:29'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class PartyKickedByMessage : AbstractPartyMessage
	{
		public const uint Id = 5590;
		public override uint MessageId
		{
			get
			{
				return 5590;
			}
		}
		
		public int kickerId;
		
		public PartyKickedByMessage()
		{
		}
		
		public PartyKickedByMessage(int partyId, int kickerId)
			 : base(partyId)
		{
			this.kickerId = kickerId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteInt(kickerId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			kickerId = reader.ReadInt();
			if ( kickerId < 0 )
			{
				throw new Exception("Forbidden value on kickerId = " + kickerId + ", it doesn't respect the following condition : kickerId < 0");
			}
		}
	}
}
