// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'AlignmentRankUpdateMessage.xml' the '04/04/2012 14:27:35'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class AlignmentRankUpdateMessage : Message
	{
		public const uint Id = 6058;
		public override uint MessageId
		{
			get
			{
				return 6058;
			}
		}
		
		public sbyte alignmentRank;
		public bool verbose;
		
		public AlignmentRankUpdateMessage()
		{
		}
		
		public AlignmentRankUpdateMessage(sbyte alignmentRank, bool verbose)
		{
			this.alignmentRank = alignmentRank;
			this.verbose = verbose;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteSByte(alignmentRank);
			writer.WriteBoolean(verbose);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			alignmentRank = reader.ReadSByte();
			if ( alignmentRank < 0 )
			{
				throw new Exception("Forbidden value on alignmentRank = " + alignmentRank + ", it doesn't respect the following condition : alignmentRank < 0");
			}
			verbose = reader.ReadBoolean();
		}
	}
}
