// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'TaxCollectorMovementRemoveMessage.xml' the '04/04/2012 14:27:31'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class TaxCollectorMovementRemoveMessage : Message
	{
		public const uint Id = 5915;
		public override uint MessageId
		{
			get
			{
				return 5915;
			}
		}
		
		public int collectorId;
		
		public TaxCollectorMovementRemoveMessage()
		{
		}
		
		public TaxCollectorMovementRemoveMessage(int collectorId)
		{
			this.collectorId = collectorId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(collectorId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			collectorId = reader.ReadInt();
		}
	}
}
