// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameFightTurnResumeMessage.xml' the '04/04/2012 14:27:24'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GameFightTurnResumeMessage : GameFightTurnStartMessage
	{
		public const uint Id = 6307;
		public override uint MessageId
		{
			get
			{
				return 6307;
			}
		}
		
		
		public GameFightTurnResumeMessage()
		{
		}
		
		public GameFightTurnResumeMessage(int id, int waitTime)
			 : base(id, waitTime)
		{
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
		}
	}
}
