// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'GameFightLeaveMessage.xml' the '04/04/2012 14:27:23'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Messages
{
	public class GameFightLeaveMessage : Message
	{
		public const uint Id = 721;
		public override uint MessageId
		{
			get
			{
				return 721;
			}
		}
		
		public int charId;
		
		public GameFightLeaveMessage()
		{
		}
		
		public GameFightLeaveMessage(int charId)
		{
			this.charId = charId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			writer.WriteInt(charId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			charId = reader.ReadInt();
		}
	}
}
