// File generated by 'DofusProtocolBuilder.exe v1.0.0.0'
// From 'FightTemporaryBoostWeaponDamagesEffect.xml' the '04/04/2012 14:27:36'
using System;
using Stump.Core.IO;

namespace Stump.DofusProtocol.Types
{
	public class FightTemporaryBoostWeaponDamagesEffect : FightTemporaryBoostEffect
	{
		public const uint Id = 211;
		public override short TypeId
		{
			get
			{
				return 211;
			}
		}
		
		public short weaponTypeId;
		
		public FightTemporaryBoostWeaponDamagesEffect()
		{
		}
		
		public FightTemporaryBoostWeaponDamagesEffect(int uid, int targetId, short turnDuration, sbyte dispelable, short spellId, int parentBoostUid, short delta, short weaponTypeId)
			 : base(uid, targetId, turnDuration, dispelable, spellId, parentBoostUid, delta)
		{
			this.weaponTypeId = weaponTypeId;
		}
		
		public override void Serialize(IDataWriter writer)
		{
			base.Serialize(writer);
			writer.WriteShort(weaponTypeId);
		}
		
		public override void Deserialize(IDataReader reader)
		{
			base.Deserialize(reader);
			weaponTypeId = reader.ReadShort();
		}
	}
}
